version: "3"

services:
  db:
    image: postgres:10.1
    ports:
    - "5432:5432"
    volumes:
    - "./dbdata:/var/lib/postgresql/data"
    environment:
    - "POSTGRES_USER=root"
    - "POSTGRES_PASSWORD=root123"
    - "POSTGRES_DB=pgdb"

  web:
    build: web
    ports:
    - "3000:3000"
    environment:
    - "DATABASE_HOST=db"
    - "DATABASE_PORT=5432"
    - "DATABASE_USER=root"
    - "DATABASE_PASSWORD=root123"
    links:
    - db
    volumes:
    - "./app:/app" #共有フォルダの設定
    stdin_open: true
    depends_on:
    - db

